### ISSUE TITLE
footer in the wrong spot

### ISSUE THREAD

**Issue by KyungjinJPark** [thomasp18/pickleball_weather_app#6]
![image](https://github.com/user-attachments/assets/02351c23-73b8-49ef-ac05-827dfd889370)
![image](https://github.com/user-attachments/assets/76e37aba-aff3-4563-9210-3065fec8beab)

**Comment by thomasp18** [comment]
🤬

**Comment by KyungjinJPark** [comment]
> 🤬

@thomasp18 - 🐒

**Comment by KyungjinJPark** [comment]
why did bro re-open the issue

**Comment by thomasp18** [comment]
> why did bro re-open the issue

i gotta fix the body spacing!
